### ISSUE TITLE
Bans page suggestion

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/FloodIssues#118]
I had an idea that we could make a bans page similar to what I have drawn. 
- Green = 1 ban on record
- Yellow = 2 bans on record
- Red = 3 bans on record
- Transparent = Permanent 

"_This idea gives better visual info overall since color would suggest a how troublesome a player is and how severe his next punishment might be_"

http://f.devinity.org/nWihgh

Feedback is appreciated,
Jeff

P.S: The above pic is just an example. The text or tiles could be edited in any way that suits the design of the forum.

**Comment by Donkie** [comment]
The colors are abit misleading, green is usually seen as something good. Bans are never good. I think just a digit is much better to put somewhere.

**Comment by jeffreythe00** [comment]
Works as well.
