### ISSUE TITLE
Give Bronze+ exclusive chat emoticons.

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/FloodIssues#145]
I would be willing to scrounge up and add some new emoticons exclusively for Bronze+ in addition to #144

**Comment by CounterCraftz** [comment]
Steam emoticons would be a nice feature to have ( steam.tools/emoticons )

**Comment by jeffreythe00** [comment]
I'll make a bunch then. C:

**Comment by CounterCraftz** [comment]
O I've meant integrating steam emoticons to hatschat 
Here's a reference https://scriptfodder.com/scripts/view/231

**Comment by jeffreythe00** [comment]
Oh. Okay! We totally should. I've been wanting to add a "RIP" icon and thought adding others might be a good idea too.
