### ISSUE TITLE
Modify draw distance

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/FloodIssues#146]
@Donkie @bayrock  

Can we have a toggle-able command so that Mod+ can see names from a further distance? This can help greatly with moderation. 

If someone was prop pushing, I could see who it is a LOT easier. (see pic)

http://f.devinity.org/WaSv6K

**Comment by Donkie** [comment]
The reason I made the draw distance short was to prevent clutter on screen. Any way around that?

**Comment by jeffreythe00** [comment]
I can't think of any way to get around the screen clutter except by making it an option. IE: A slider that adjust view distance.
