### ISSUE TITLE
Weapon damage recalibrations vs. zombies

### ISSUE THREAD

**Issue by ghost** [GMDevinity/FloodIssues#179]
: )

**Comment by CounterCraftz** [comment]
Healing stick's damage should be relatively higher since swing speed is slower than crowbar. (Probably 150 would be nice)

**Comment by DawsonDevinity** [comment]
Got it.  Thanks for the input.

**Comment by Donkie** [comment]
Isn't it better if we divide these values by 7, (so the damages are for players with 100hp), then add a column to the database for "pvpdamage" per weapon.

Then during zombie event, we allow PvP Damage, and increase dmg of weapons by 7x.

That way, you guys can easily change these values, and we're future ready incase we add more events with pvp damage.

**Comment by DawsonDevinity** [comment]
^ I like that approach.  The same could probably be done with Juggernaut.
