### ISSUE TITLE
Thrown Items + Smart Weld Improvements

### ISSUE THREAD

**Issue by Jiwer** [GMDevinity/FloodIssues#197]
Hey, so I recently found out that if you hold Sticky TNT until the animation has finished and holster it, after pulling it out again it will automatically throw. After talking to Dawson about this he said it was old news and that it occurs on other thrown sweps like the molotov and grenade. I took it opon myself to take a look at the Sticky TNT code and see if I could figure anything out. At first I thought that the fuse should just reset when holstering it, but what made more sense was to not let someone holster a bomb about to explode.

You could check if animstep doesn't equal nil in SWEP:Holster and if so return false like so.

```
function SWEP:Holster()
	if self.animstep then
		return false
	end
end
```

Also I thought it would be really cool if a feature was added to smart weld where when holding down a key and clicking a prop it would select all of your props in a radius. This would make building so much quicker for players that have a big boat, as well as lessen the occasions where players didn't have time to finish welding their boat. I did this by replacing lines 75-80 with this.

```
if ply:KeyDown(IN_SPEED) then
	for k, v in pairs(ents.FindInSphere(trace.Entity:GetPos(), 500))
		self:Select(v)
	end
else
	if self:IsSelected(trace.Entity) then
		self:DeSelect(trace.Entity)
	else
		self:Select(trace.Entity)
	end
end
```

Adding a convar and using that as the radius would be better than a hard coded amount. You should also add a note in the tool's help text letting players know of this feature.

I know you know how to do all of this stuff Donkie, but I understand you have a life and stuff, and I just thought I'd take a little bit of work off of you to hopefully push out some updates a little faster.

**Comment by Jiwer** [comment]
Wow github code quotes are ass.

**Comment by DrPitLazarus** [comment]
You need to do triple backticks for code block. I edited it for you. :)

**Comment by Jiwer** [comment]
You forgot the if ply:KeyDown(IN_SPEED) then line at the top.

**Comment by Donkie** [comment]
Good stuff, smart weld is a lazy man's tool and I removed the existing radius select because it got too easy. Maybe with the weld distance limit I added tho it might be good to get the radius select back
