### ISSUE TITLE
Some Suggestions 

### ISSUE THREAD

**Issue by Jiwer** [GMDevinity/FloodIssues#200]
~~Format the displayed money strings. 
Ex:
1000000 =
1,000,000~~

Maybe lower the zombie health a bit, with the server being 33 tick and the damage our weapons do it's really difficult to kill zombies. I have to throw away like 1 clip of the para just to kill one zombie. What about players that don't have a para? What happens when two zombies start to fuck you? Come on one of the populated servers, force a zombie round, and you'll see exactly why I think it should be changed.

Could the zombies do damage after their animation gets played? It makes a little more sense.

I was talking to some of my old friends that I used to play Devinity with and we thought it would be a neat idea if US #3 had an old flood version on it. As far as how old, I thought that 2013 flood was a little too underdeveloped and lacking, so maybe early to mid 2014? It's just an idea and out of the few people I talked to they thought it would be fun to go back a little. I personally would actually play on it, US #3 is always empty anyways. If you were to do it a second db would be needed though.

**Comment by CounterCraftz** [comment]
If we were to lower the zombie's health, respawn time should lower as well.

It'd be nice if the idle/attack anims are changed for zombies (should look into Zombie Survival's code)
http://f.devinity.org/W1yrDS - Idle

I definitely support replacing US3 with an older version/commit of flood, a separate leaderboard would be nice too

**Comment by Donkie** [comment]
Please make one issue per issue, unless its really minor things, then please make one issue with a neat checkbox list.
