### ISSUE TITLE
Preventing Easy Weld tool abuse

### ISSUE THREAD

**Issue by ghost** [GMDevinity/FloodIssues#203]
: )

**Comment by CounterCraftz** [comment]
Getting rid of "easy weld" would be easier instead of having Donkie to go through the extra work. Players have been abusing the tool regardless; I would see them sabotaging others boats during team-based events and trying to crash the server.

**Comment by DawsonDevinity** [comment]
When used for non-malicious purposes, it's a nice tool.  However we'll have to hear what Bayrock/Donkie wants to do.

**Comment by Donkie** [comment]
Would be pretty difficult finding out if they intertwine or not I'm afraid

**Comment by jeffreythe00** [comment]
Just wanted to clarify that people abuse regular weld during team based events too. It's not just a smart weld thing.
