### ISSUE TITLE
Stagnation in pirate rounds

### ISSUE THREAD

**Issue by RicksBeehive** [GMDevinity/FloodIssues#268]
Towards the end of the round pirate rounds can become stagnated because players run out of methods to move around and don't want to take damage by swimming to their target. Chests have done a bit to improve this but it still sort of happens.

I've come up with some ideas as to how to make this less stagnant. (I dont think more than one of them will ever be needed ofc, just a few ideas)

**Whirlpool**
After some amount of time, props experience a force towards the centre of the map, forcing the players to fight against eachother.

**Weathering**
This round has been suggested in the past as a standalone round. I think it'd work better as a part of the pirate round.

Over time, props should take accelerating damage starting at 0 per second and reaching something like 3 per second after a few minutes. This would mean that the number of props in the map would be decreased over time, forcing players to swim to a fewer and fewer number until they are forced together.

**Scurvy**
Pretty simple, if the player hasn't dealt damage in the  last [x] seconds, they begin to take damage. Maybe we could have a lemon icon which slowly disappears as you get closer to this time limit?

**Comment by Donkie** [comment]
Whirlpool would be pretty badass and simple to code

**Comment by RicksBeehive** [comment]
Probably doesnt need to be visible. Could just have it mentioned in the popup at the start of the round and have a sound effect?
