### ISSUE TITLE
Revamped Stats Page

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#285]
![stats](https://cloud.githubusercontent.com/assets/11022368/23834564/e5097532-072e-11e7-8ddc-c4f002993b82.png)

monthly stats can get removed if you're not a fan of it

**Comment by Donkie** [comment]
The last 3 rows of stats are currently not logged so they will be more difficult to add. 
However the other rows are very doable! 

#makestatspagegreatagain
