### ISSUE TITLE
Some minor ideas.

### ISSUE THREAD

**Issue by CcLLL** [GMDevinity/FloodIssues#365]
- Implement achievement for buying the predator missile.

- Include infraction page on the scoreboard (when right clicking on a player.) view the playerteamid

- Make a brief describtion what the gamemode is about, i see so many new players ask how to make an boat float etc, of course i can help with that though.

- The !motd will automatically pop out when joining the game, where you have to wait 15 seconds before it closes

- When making a ban in chat convert it to days instead of minutes.

- Allow moderators to physgun/toolgun other props since they have access to !clean

**Comment by CounterCraftz** [comment]
most ideas have been implemented via escape
