### ISSUE TITLE
Welfare System

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#414]
Add back the welfare system (going to reiterate some existing features)
- [ ] Remove cooldown
- [ ] Give players $2000 if they have less than $1000 on their wallet
- [ ] **Restrict players from giving money/purchasing or selling tokens for 24-48 hours** *(to prevent abuse)*

**Comment by ViralDevinity** [comment]
Sorry to revive pls no banerino

Free props are "okay" but they aren't good enough to help out people with no money, they last no time at all and you can't buff them or they get abused by experienced players. 

A way to implement the welfare system in a way that would prevent abuse is to add a limit to how much money you can receive from it as suggested by Jeffrey.

- Once you go under $600 (amount used to create the common vending machine boat) you're given a $1000 with an on-screen notice telling them they've used $1000 out of their $10000 daily limit on welfare (this is open to change). 

- When the user has been given welfare reduce the price of props for them to 3/4 of their original price to encourage them to build boats that will survive. 

- Remove the ability to give money to other users after receiving welfare until they hit a certain amount of money E.G $5,000.

- Introduce more viable free props that will appeal to those who need them but also won't be used by experienced players, the free props were good as they were to some extent, just the wrong people used them (or add a level limit or something).
