### ISSUE TITLE
Toggleable Stat Panels for HUD

### ISSUE THREAD

**Issue by DrPitLazarus** [GMDevinity/FloodIssues#43]
look who's late to le githubs
Thread: http://devinity.org/threads/toggleable-stat-panels-for-hud.2624/

**Comment by Donkie** [comment]
While numbers are always fun, I don't think this is something worth spending time on. Some of the build phase stats have already been added, and seeing a bunch of half-irrelevant numbers on your screen during fight might be distracting.

**Comment by CounterCraftz** [comment]
Yes and no

I feel like players should have more creative freedom to build cool looking towers and contraptions that might require more than the current height limit 

They should be able to build higher up (about the same dimension length/width wise of the room) but the consequence of that will be that players are be able to see what you're building exactly, I think that's a pretty fair tradeoff

**Comment by CounterCraftz** [comment]
Fuck wrong issue
