### ISSUE TITLE
JUST DO IT (meme lol) --> Expand prop refund feature

### ISSUE THREAD

**Issue by RicksBeehive** [GMDevinity/FloodIssues#445]
When a player dies, another player attacking gets no profit from destroying dead props ok!
But the player that has his props destroyed (The dead player) does lose money because of the refunds (Based on health of props at end of the round)

Remove this health refund shit, either save it as soon as the player dies or remove refunds and change the economy accordingly.

TLDR Prop farming is still an issue

**Comment by Donkie** [comment]
Fixed
