### ISSUE TITLE
Zombie Event Rework 

### ISSUE THREAD

**Issue by ViralDevinity** [GMDevinity/FloodIssues#454]
# Zombie Event
Potential fixes intended to increase the length of the round and allow humans to live longer. Currently, zombies overpower players and become the focus of the round very quickly, taking away from the actual gameplay.

- Reduce money earned whilst playing as a zombie to $3/sec, or remove money earning entirely. 

- Implement a damage-based reward for assisting in a kill on a player. 

- Decrease cost of props or increase monetary gain as a human, similar to haste round.

-  Decrease zombie damage to 3/4, to make them more of an annoyance than a threat.

- Reduce the damage of the healing stick or implement a sweeping blow feature to the sledgehammer to balance the two. Also, implement the same amount of knockback between the two weapons, Non-VIP's should still be granted the same amount of knockback.

- Increase initial respawn time to 15 seconds, to prevent spawn damage whilst the alive are unable to fight back.

- Decrease money gained per hit to $8 to factor in the lesser damage.
 
- Make zombies move slower than humans and allow them to do tiny amounts of damage to props (2.5-3). The map is small, moving that quickly is ridiculous. This fix will probably remove the ability to super jump onto tall boats, but the damage will give them the ability to destroy the props instead, increasing money gain.

- Decrease health of zombies to 600 and make them take the same amount of damage from the water that humans take but decrease respawn time to 15 seconds.

Thanks to Noriaki for assisting in some of the ideas.

**Comment by CounterCraftz** [comment]
Most of these changes are now feasible through Donkie's PvP damage database implementation

Making zombies weaker can be done through increasing weapon damage output
