### ISSUE TITLE
New weapons feedback

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/FloodIssues#455]
Post any changes that needs to be done to the new weapons here

**Comment by Donkie** [comment]
* Increase bazooka rocket gravity (flies too straight atm)

**Comment by exotranc** [comment]
- Compound bow fires once and cannot be fired again, also does 0 damage

**Comment by ViralDevinity** [comment]
Reduce recoil and spread of TMP.

Decrease damage dealt by the XM1014/Reduce fire rate.

Increase Grenade Launcher damage to 20(?) to compensate for the extra reload time. 

Decrease UMP damage to 4, 5 is just broken.

Increase recoil and firerate on AK-47.

Increase AUG damage to 2.5 and decrease recoil. 

Decrease Glock damage to 2 to counteract the rapid-fire speed.

**Comment by Donkie** [comment]
![image](https://user-images.githubusercontent.com/2332094/37559423-1e4b3a68-2a26-11e8-8189-ca5c1cbdce96.png)

**Comment by Donkie** [comment]
![image](https://user-images.githubusercontent.com/2332094/37559520-03a9d10e-2a28-11e8-9ad9-fecefb4b711d.png)

**Comment by manchyy** [comment]
- Reduce horizontal recoil on Deagle.

**Comment by Donkie** [comment]
![image](https://user-images.githubusercontent.com/2332094/37559599-2b202e8a-2a29-11e8-8811-06f620d0de6d.png)

**Comment by exotranc** [comment]
- Increase prices of assault rifles or lower prices of SMGs

**Comment by Donkie** [comment]
Further nerfed shotgun

![image](https://user-images.githubusercontent.com/2332094/37559737-3c8cf3fe-2a2b-11e8-96b7-3add698de56d.png)

**Comment by Donkie** [comment]
✔️ Reduced bazooka rocket velocity, is now much like it was before
✔️ Bazooka rockets now explode on water contact
✔️ Removed weapon range falloff
✔️ Fixed events having incorrect weapons

**Comment by ViralDevinity** [comment]
Add drop to the grenade launcher (can currently fire across map).

**Comment by exotranc** [comment]
- You don't spawn with the healing stick

**Comment by manchyy** [comment]
- Grenade launcher unwelds props (why buy bazooka then)

**Comment by ViralDevinity** [comment]
Reduce fire rate of the AWP, remove knockback when hit with Grenade Launcher and Rocket Launcher, harpoon has no rope clientside.

**Comment by CounterCraftz** [comment]
compound bow damage is displayed but barely visible

**Comment by ViralDevinity** [comment]
- Reduce travel speed of the rocket launcher's rocket.

**Comment by CounterCraftz** [comment]
changed m249's spread from 0.05 to 0.1
changed deagle's damage from 15 to 12
changed 5-7's damage from 4 to 5 again
changed glock's clipsize from 16 to 32

**Comment by ViralDevinity** [comment]
- Remove crouching accuracy, it makes the guns have like 0 recoil.

**Comment by CounterCraftz** [comment]
change scope of awp and g2 contender to the one used on fmbase

**Comment by ViralDevinity** [comment]
Lower sensitivity on scopes, or add a slider in Settings so users can customize the sensitivity to their own taste.

**Comment by CounterCraftz** [comment]
changed ump45's damage to 5
also changed up, down and horizontal kick to 0.5

**Comment by exotranc** [comment]
Setting default weapon is broken for some, you take out the bazooka for a few seconds and then switch to the contender

**Comment by ViralDevinity** [comment]
- Reduce famas fire-speed.

- Decrease Galil ammo capacity.

**Comment by CounterCraftz** [comment]
changed famas's rpm from 925 to 900

**Comment by ViralDevinity** [comment]
- Add a stat when you hover over the weapons you can see their fire rate.

**Comment by CounterCraftz** [comment]
decreased m249's damage from 6 to 5
rpm has been changed from 900 to 800
up,down and horizontal kick changed from 0.5 to 0.8

**Comment by exotranc** [comment]
- Increase crowbar attack speed, it hits rather slowly now

**Comment by Donkie** [comment]
✔️ Fixed bow arrow hit numbers being hidden
✔️ Reduced bazooka rocket speed further
✔️ Fixed healing stick
✔️ Disabled dynamic accuracy (crouching no longer increases accuracy)
😿 Can't fix rockets/grenades knocking people back since they're physical objects

**Comment by manchyy** [comment]
Harpoon's viewmodel is bugged out.

- Harpoon viewmodel only bugs out when you deploy it. (e.g. shooting it onto a wall).
- It happens with any prop, tested with: bookshelves, bouncy castle, vending machines.

![20180319153426_1](https://user-images.githubusercontent.com/37485545/37605802-ecb90752-2b8b-11e8-966b-3220a6a6ce0b.jpg)
![20180319153429_1](https://user-images.githubusercontent.com/37485545/37605804-ecf83c1a-2b8b-11e8-98b6-26b247a3d519.jpg)
![20180319153647_1](https://user-images.githubusercontent.com/37485545/37605803-ecd93d42-2b8b-11e8-87f0-4ee4b2f8726e.jpg)

**Comment by ViralDevinity** [comment]
- SG Needs a recoil nerf, you can pretty much just spray the full mag into a prop unless it's pretty thin.

- Increase ammo capacity for the SG.

- Revert the compound bow back to its former self, it's a poor excuse for a weapon currently.

**Comment by exotranc** [comment]
- Playerstats appear to track weapons incorrectly so far
- You can put an extra round in the chamber with TFA weapons but they do not appear on the ammo bar in the bottom left
- When you empty the XM1014's magazine, it reloads one shell, stops, and reloads the rest; if possible, remove this because no other weapons have different reloads for empty magazines

**Comment by ViralDevinity** [comment]
- Reduce the rocket's travel speed (again), it still travels way too fast.

- Increase Five-SeveN's clip size to 20.

- Reduce recoil on the m249.

- Increase the m249's damage back to 6, you're paying 25,000 for something that does the same damage as an SMG. 

- Decrease the M4's fire rate. 

- Decrease the Famas' fire rate.

- Increase the M3 Super 90's spread, it still does like 40 damage at medium range.

- Decrease the Glock's price to $9,000, the extra $250 is just stupid. 

- Increase harpoon capacity to 6.

- Reduce AWP fire rate.

- Reduce sideways recoil on the UMP and add more vertical recoil.

**Comment by SergeantOrange** [comment]
- Reduce the damage of the AK47 back to 4, its currently the top tier rifle.

- Make the FAMAS more accurate but with slightly less rpm.

- Change the smoke and explosion effects of the bazooka back to the old one, my framerate dips to 20 when its fired.

- Make the shotguns behave like older hl2 ones, you had to fire them in pretty creative ways and it actually added an element of skill in the game.

- Add better scope textures for awp and sg, current ones are workable but the old ones were nice.

- Nerf the ump damage to 3 or 4 but buff its accuracy heavily.

About the rockets knocking back people, you can always copy the rocket entity from the previous weapons and use that as the rocket

**Comment by exotranc** [comment]
- Edit descriptions for bookshelves and other props that were pierced; they say they are susceptible to arrows

**Comment by ViralDevinity** [comment]
- SG550 Reload sound gets looped occasionally. 

- New weapons cause occasional lag spikes.

- Increase healing stick output to 5 damage per hit and reduce the number of times it can be used.
