### ISSUE TITLE
restrict weapons/cosmetics if not vip

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#456]
there should be add a check if players bought VIP cosmetics/weapons and they're not VIP, the weapon should be restricted or stripped when fight phase begins or the cosmetic should immediately be dequipped on spawn

**Comment by exotranc** [comment]
Is this to prevent foul play or to just disallow former mods who have purchased the VIP items in the past?

**Comment by CounterCraftz** [comment]
disallow former mods and VIP members who were demoted

**Comment by SergeantOrange** [comment]
What about the ones who resigned on good terms, should we punish them?

**Comment by CounterCraftz** [comment]
If they're not VIP, they shouldn't be able to receive the rewards regardless of the terms. Better safe than sorry

**Comment by ViralDevinity** [comment]
I think this is a good idea and all, but if they left on good terms then they should be allowed to keep the items, a "thank you" gift for the support they gave to the community.

**Comment by CounterCraftz** [comment]
I still don't think staff who aren't on our team should receive such benefits due to some people taking direct advantage of it. If people left on good terms, then we admins can decide to give them a VIP rank.
