### ISSUE TITLE
increase spectator fov

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#458]
Increase the FOV so it doesn't look like this
![image](https://user-images.githubusercontent.com/11022368/37561604-17402af0-2a29-11e8-9711-25e227cd9e42.png)

Instead it should look like the player's normal view
![image](https://user-images.githubusercontent.com/11022368/37561609-27fcf616-2a29-11e8-94e4-e92e19dd4266.png)

**Comment by Donkie** [comment]
Are you sure its the client's camera FOV being affected and not just the viewmodel being offset/changed fov?

**Comment by Donkie** [comment]
Are you sure its the client's camera FOV being affected and not just the viewmodel being offset/changed fov? @CounterCraftz

**Comment by CounterCraftz** [comment]
it's been apparently fixed now
