### ISSUE TITLE
Miscellaneous Event Changes

### ISSUE THREAD

**Issue by ViralDevinity** [GMDevinity/FloodIssues#460]
# Event Changes
So far I believe the current events are "good", but not great, and they could indeed be better. 
### Acid Event

- Make it so that the acidic water only takes effect once the water has fully risen, props lose 64 health just in the rising stage, which for most props is a huge chunk.

- Decrease the damage from 4/s to 2-3/s, events are supposed to be fun, "rare" occurrences, having them last a few seconds ruins the fun, at least for me.

### Rope event

- Remove the limit on rope connects, or at least increase it to 2/3, this will help people create more sturdy boats and not ones that just get ruined because they couldn't rope them enough. 

- Give props half cost, this is an event, props shouldn't cost full price. 

### Team Event

- Fix the long lasting bug whenever you join during a team event you aren't placed on a team.

### One Weapon Event

- Remove double damage, it isn't a haste event so the round shouldn't need to go any faster.

- Add more variety of weapons, so far I've only seen a select few weapons used in the event, maybe add the famas to the event to give normal users a taste of the weapon. 

- Remove things like the grenade from this event, some boats they just slide off and explode underwater, making them useless, they also make the round really long. 

### Build to the Top

- Fix the bug where props are removed above water level.

- Readd the event back to the event pool.

All of these are subject to change and more will probably be added to it.

**Comment by Donkie** [comment]
Done most, team event bug is already in another issue
