### ISSUE TITLE
April Fools

### ISSUE THREAD

**Issue by ViralDevinity** [GMDevinity/FloodIssues#464]
This issue is for the 2018 April Fools "event". 

### Forums
- Force "vaporwave" skin to all users.

- Change all forum pictures to the default question mark (?)

### Servers
- Force "Obese Male" (or some other "meme" playermodel).

- Change a commonly used prop; E.G the large bookshelf, and change the properties of it to something unusable such as a lack of buoyancy or a substantial health decrease.

- Make all the props display that they only cost $1, but keep actual pricing (maybe not this one since it _could_ cause some confusion.

**Comment by SergeantOrange** [comment]
Thing about april fools is, garry will probably already have a prank ready like that super annoying runescape one last year
