### ISSUE TITLE
Loading screen doesn't appear to be working

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#469]
[![](https://img.youtube.com/vi/GErkBwgf0N0/0.jpg)](https://youtu.be/GErkBwgf0N0?t=34s "Click to play on Youtube.com") (video)

affects other clients as well (name, cash, playtime won't load correctly)

**Comment by DrPitLazarus** [comment]
<b>Fatal error</b>:  Call to undefined function DBCreate() in <b>/var/www/loading.devinity.org/public_html/fm/grabavatar.php</b> on line <b>50</b>

**Comment by Donkie** [comment]
Fixed, thanks
