### ISSUE TITLE
Unable to toggle thirdperson

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#470]
[![](https://img.youtube.com/vi/0lBQbyGudX4/0.jpg)](http://www.youtube.com/watch?v=0lBQbyGudX4 "Click to play on Youtube.com")

**Comment by Donkie** [comment]
It only works sometimes. Has something todo with TFA.

**Comment by CounterCraftz** [comment]
Yeah, I was about to post that as soon as I was able to toggle CTP. Could it perhaps have to do with forcing firstperson when ironsighting?

**Comment by Donkie** [comment]
Yeah definitely

**Comment by CounterCraftz** [comment]
Can confirm player being unable to toggle thirdperson until ironsights are used for the first time on fight phase

**Comment by Donkie** [comment]
Fixed
