### ISSUE TITLE
Fix pls

### ISSUE THREAD

**Issue by ViralDevinity** [GMDevinity/FloodIssues#473]
Whenever you warn a team it doesn't give them all an infraction feelsbadmen

**Comment by Donkie** [comment]
I see no apparent issues in code, care to elaborate? Who gets the infraction? Does anyone get an infraction? Does more than 1 person get an infraction? What does the message tell you? Is there any errors in server logs?

**Comment by ViralDevinity** [comment]
From what I was told only the leader of the team receives the warning, I can test it if you need.
