### ISSUE TITLE
Implement plydmg to weapons config table

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#474]
so we could make reasonable changes to damage dealt against zombies

**Comment by CounterCraftz** [comment]
Can it be possible to use SWEP.PrimaryDamage as damage for the zombie event if it's not already used for the prop

Could be useful to display info for this PR (https://github.com/Donkie/floodweapons/pull/36) instead of using flood wepdamage

**Comment by Donkie** [comment]
Done
