### ISSUE TITLE
Lamps and Lights don't despawn and they are performance-heavy.

### ISSUE THREAD

**Issue by manchyy** [GMDevinity/FloodIssues#479]
### Lamps and Lights don't despawn
They stay in the server even if the person has left. They never despawn unless the server restarts or an admin removes them.

This makes the game barely playable, since it hits the performance hard. On this rig (i7-930+1070) it made the framerate jump to 15-20. After I removed them it jumped back to **stable** 100+. Imagine the framerate on weak computers.

### Give moderators permissions to remove them and/or set a timer for them to despawn.
When I used to be a moderator I remember not being able to remove the lamps and lights. !cleandecals command doesn't remove the entities. This makes it really frustrating when trying to play and having to ask an admin to either remove the lamps. I know there has to be a barrier between what an admin and moderator could do, but this has to be at least few of the players' structures that moderators can remove using the remover tool. 

**Screenshots**
![20180526171258_1](https://user-images.githubusercontent.com/37485545/40577184-155508b0-610a-11e8-830e-33560639f747.jpg)
![20180526171259_1](https://user-images.githubusercontent.com/37485545/40577185-17233450-610a-11e8-8c41-70a06a238be2.jpg)

**Comment by Donkie** [comment]
Should be fixed
