### ISSUE TITLE
Remove red death screen

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#480]
This occurs especially on the zombie event, after you die and the red death screen appears, it will stay throughout even if you're alive unless you kill yourself ingame (which sometime doesn't work as well). 

It's not aesthetically pleasing and hopefully will remediate annoyances in the game that might deter players from playing

https://gmod.facepunch.com/f/gmoddev/lqhp/Remove-red-effect-from-player-death/1/
https://steamcommunity.com/groups/gmod/discussions/0/810923580585135009/

**Comment by Donkie** [comment]
not sure what this means, the red screen shouldn't be visible when you're alive?

**Comment by CounterCraftz** [comment]
It does display the red screen, but on certain occurrences 
I think it has to do with dying in water before the next phase pops in

Found a gameplay footage of the exact scenario
https://www.youtube.com/watch?v=vM8XHMlkvP4

**Comment by SergeantOrange** [comment]
I think the red screen should just be removed, its plain ugly, glitch or no glitch
