### ISSUE TITLE
Remove waterfall ambient

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#481]
ambient/levels/canals/dam_water_loop2.wav

This has been playing on the sewer pipes and is a major disturbance constantly having to listen to it, obscuring phase music, building
#363 

players don't have to stopsound without also having the music stop

**Comment by CounterCraftz** [comment]
I might create a workaround that replaces the sound with a blank .wav file, the same method people have used to get rid of the barking sound on a roleplay map

https://gmod.facepunch.com/f/gmoddev/lsri/Problem-with-Evocity/1/
https://steamcommunity.com/sharedfiles/filedetails/?id=520636892

**Comment by Donkie** [comment]
messed around with this abit and its pretty wonky to do from code, replacing with an empty .wav file sounds better.

**Comment by CounterCraftz** [comment]
added new .wav file to community content 1
