### ISSUE TITLE
issue in flood

### ISSUE THREAD

**Issue by mantis2** [GMDevinity/FloodIssues#490]
Today I was playing flood and I was about to ban this person but when I tried I got script errors saying this       [ERROR] gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/cl_score.lua:124: attempt to compare number with string
  1. OpenBanPopup - gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/cl_score.lua:124
   2. DoClick - gamemodes/flood_ssgbn56sbcyujtma13gi9g9ru3gh1c84mhxsj/gamemode/cl_score.lua:211
    3. OnMouseReleased - lua/vgui/dlabel.lua:232
     4. unknown - lua/vgui/dmenuoption.lua:77

**Comment by Donkie** [comment]
Fixed!
