### ISSUE TITLE
Option in settings to disable loose prop removal

### ISSUE THREAD

**Issue by exotranc** [GMDevinity/FloodIssues#491]
The setting would be on by default, but for people who know what they're doing they might want to turn it off. I like to use single prop backup boats and they get deleted since it is considered a loose prop.

**Comment by CounterCraftz** [comment]
Don't think this would be a good idea. 1 prop boats aren't proper boats and should be discouraged

**Comment by exotranc** [comment]
What I mean by single prop backup boat is something the likes of an inflatable raft, which is already a "boat" on its own. It doesn't make sense for something like that to get deleted. Maybe we can add a flag to some props that indicate they can be used on their own so they don't get deleted.

**Comment by Donkie** [comment]
The loose prop removal only kicks in if you have more than 3 props, and it never leaves you with less than 3 props.

If you want the raft as a backup boat, you can just rope it to your main boat and it doesn't count as a loose prop.

The loose prop cleanup system's point is to reduce lag by removing props people have forgotten about.

**Comment by exotranc** [comment]
That's why I want it to be an option that players could disable for themselves. When they are familiar with the gamemode and aren't leaving props everywhere, turning it off wouldn't make much of a difference in lag reduction.

**Comment by Donkie** [comment]
I don't think it should be the players choice. If the system is annoying or unclear we should work on improving that instead.
