### ISSUE TITLE
List of Suggestions + Bugs:

### ISSUE THREAD

**Issue by CozyDunG** [GMDevinity/FloodIssues#494]
**Flood:**
- [x] Flash freeze round - The weapons that we are given during fight on this particular event are not what we equip
- [x] Random loadout event (shhh) - Dakdak (autosniper) is no longer a silent weapon, remove it and instead, add m4 with its silencer
- [x] Explosives - They sometimes do not damage particular props (1 ton, large wooden basket, small plastic basket) + Explosives need to be nerfed. Explosives just destroy every prop lower than 150 hp which is basically 1/2 of the props.
- [ ] Melee weapons - Fix the throwing mechanics + add a knockout feature. By throwing a crowbar, it knocks the player idle for 3 seconds upon hit, a sledgehammer doing 4 seconds
- [ ] Add a prop which is similar to the lifeguard boat and bouncy castle (relatively large) but less health and more easy to afford.
- [ ] A new weapon called Weld tool (Different version from build phase) - The gun has a pretty long cooldown period of 5 seconds but you do not have to "reload" it. The gun should have max of 5 bullets.  The gun is able to unweld / weld your or the enemy's props completely. Welding mechanics should be similar to that of building phase. However, to unweld, the player must steadily shoot at the prop for an extended amount of time (eg 3 seconds) before the prop unwelds. When it unwelds, the prop completely detaches from the boat as every prop that was welded to that prop is no longer. If this is op, we can nerf it so that it takes longer at a further distance + add a distance limit.
- [ ] Victory songs + effects. We could possibly add victory songs + effects for players when they win. They could possibly buy this from the shop. 
- [ ] Prop Buff - I'd like some props to be buffed such as the devinity logo, it does not match its price and it's too easy to destroy

**General**
- [ ] Vips getting discounts upon purchase on tokens. Both Irl money and in-game money. As you mentioned, possibly 40% using irl money and maybe 15% through in-game money. 
- [x] Add a search function in jukebox so that you can find a specific song.
- [x] Also When going into jukebox, you should show what song is currently playing. (atm you can only see it when the song starts playing or scrolling up in chat)

**Comment by CounterCraftz** [comment]
Explosives has been recently changed
The idea of adding a stun on melee weapons has been previously shut down before on a conference from long ago
Prop-related changes have been noted on the latest github
You can suggest songs on our forums thread
I think the idea of giving VIPs a discount would be an okay idea, will post that on another related github issue
