### ISSUE TITLE
Bazooka not dealing damage

### ISSUE THREAD

**Issue by lightclaw** [GMDevinity/FloodIssues#508]
### Description of bug
During my play time on the server I've noticed that bazooka does not deal damage 100% even if you hit a direct on the boat. It seems that this weapons doesnt like certain props and therefore not doing anything to them.

### What I expected to happen
When I hit anything with a direct hit, I'd expect it to take damage.

### What instead happened
Instead it doesnt take damage.

### Steps to reproduce
* Build a Marine buoy+ceramic cylinder
* Attempt to shoot the buoy
* Dont deal damage

### Extra info (evidence, logs, etc)
AFAIK splash damage is server-sided, so the only evidence I can give are the demo files. We've figured that it will happen 100% to marine-buoys with ceramic cylinder.
In the field recording: https://lc.dbot.serealia.ca/screenshots/2018/08/splash.dem
Recreated in a laboratory: https://lc.dbot.serealia.ca/screenshots/2018/08/test.dem
It does work when the props are close to walls: https://lc.dbot.serealia.ca/screenshots/2018/08/test2.dem
And the bazooka is probably not working correctly with a narrow variety of props: https://lc.dbot.serealia.ca/screenshots/2018/08/1234124.dem

````
console logs are provided in test.dem
test.dem files were recorded at ~11:10 PM CEST, 4th of August, 2018 on US#1 server.
````

**Comment by CounterCraftz** [comment]
![image](https://user-images.githubusercontent.com/11022368/43913639-a197539c-9bd3-11e8-8059-a3726a8f8e74.png)
@Donkie does enabling this convar fix anything or is it just simply a hitbox-ish issue?

**Comment by Donkie** [comment]
Still relevant? @CounterCraftz @lightclaw

**Comment by CounterCraftz** [comment]
Yes, this goes beyond just the buoy

Not all props will receive explosion damage on a normal boat construction as well

**Comment by CounterCraftz** [comment]
Won't be an issue anymore with the new launcher (removed penetration code)
