### ISSUE TITLE
Replacing the flamethrower?

### ISSUE THREAD

**Issue by Zzoppa** [GMDevinity/FloodIssues#509]
Recently I saw in the discord that the flamethrowers want to be removed due to a large number of decals. I immediately had an idea, than it can be replaced.
So.
Title: Gauss gun
Damage: 25
Ammo: 5
Clip size: 1
Cost: 40000 $ (Well this is a replacement for a flamethrower)
Its main feature is that every ammo pierces through absolutely all the props.
Model: I'm not sure exactly which one is right, but I really like this: p https://steamcommunity.com/sharedfiles/filedetails/?id=646754302

**Comment by CounterCraftz** [comment]
https://github.com/Donkie/floodweapons/pull/25
