### ISSUE TITLE
Life Preserver failing to float during fight phase.

### ISSUE THREAD

**Issue by Sotoriiiiiii** [GMDevinity/FloodIssues#511]
### Description
Occasionally when spawning Life Preservers, I've seen them fail to float when the fight phase starts.

### What I expected to happen
I expected the props to float, so I could have a backup boat for when my main boat build gets destroyed.

### What instead happened
The prop stayed on the ground as if no water was occupying the space around it.

### Steps to reproduce
* Spawn 1-2 Life Preservers
* Let fight phase start
* Life preservers have a chance to not float for whatever reason

### Extra info (evidence, logs, etc)
I could not find any LUA errors or console logs explaining the prop failing to float.
![screenshot 143](https://user-images.githubusercontent.com/38799223/43845897-0fcad822-9afb-11e8-914f-12a4e796e848.png)
![screenshot 144](https://user-images.githubusercontent.com/38799223/43846097-8310f8ca-9afb-11e8-9cb0-b5f425bda4fb.png)

**Comment by CounterCraftz** [comment]
That sometime happens unconditionally when you don't physgun right away when spawning them

**Comment by CounterCraftz** [comment]
The life raft and bouncy castle are 2 other perfect examples that does this

**Comment by CounterCraftz** [comment]
Maybe it has something to do with the .qc physmaterial since it wasn't intended to float. It's not really a noteworthy issue but I'll check it out regardless
