### ISSUE TITLE
MK3A2 grenade still occasionally does random damage

### ISSUE THREAD

**Issue by exotranc** [GMDevinity/FloodIssues#517]
I'm not sure what the conditions are for it to do random amounts but I think it did something like 37.73 or around there. I saw that the props that were damaged had .27 as a decimal of their health.

**Comment by exotranc** [comment]
I think I've found something that may cause it. So far, it seems like the last grenade does more damage than the rest of them. This also happens with the MP5 grenades. This issue is pretty important so we should do a bit more research on it.

**Comment by CounterCraftz** [comment]
see reference

**Comment by CounterCraftz** [comment]
A possible solution for the issue aforementioned is by reverting back to the old fm frag grenade (regardless of the majority vote in #polls) so much coding work isn't required but may also have to be tested

**Comment by CounterCraftz** [comment]
reverted back to weapon_fragfm
