### ISSUE TITLE
Gift drops during afk

### ISSUE THREAD

**Issue by lightclaw** [GMDevinity/FloodIssues#519]
### Description of bug
You can receive gift drops while you are being afk

### What I expected to happen
be afk

### What instead happened
Free tokens flowing into your pocket

### Steps to reproduce
*Join server
*!afk
*Receive free money

### Extra info (evidence, logs, etc)
no console logs only [this](https://lc.dbot.serealia.ca/screenshots/2018/08/20180818004523_1.jpg)

I can suggest instead of using random drops to players adopting something close to the old tf2 system: the server spawns an invisible cube that will guarantee a drop once the player hits the cube. Make lots of fixed respawn points of those cubes within spawn area and dont spawn them inside the room. Or make random spawns within the player spawn area.

**Comment by Donkie** [comment]
Fixed, thanks 👍
