### ISSUE TITLE
Evaporation don't work

### ISSUE THREAD

**Issue by Zzoppa** [GMDevinity/FloodIssues#520]
Already for a long time I have encountered the problem that the achievement of "Evaporation" does not work. Presumably after weapons refund.
Before the destruction of snowmen I had 17, after their destruction I also left 17
![default](https://user-images.githubusercontent.com/28789215/44370662-3c8e5c80-a4ec-11e8-9ad3-8449369a439c.png)
Also a video that shows that I don't get an achievement, although I've destroyed enough props.
https://www.dropbox.com/s/26g4r2hzpjyxzt6/Snowbug.dem?dl=0

**Comment by Donkie** [comment]
@CounterCraftz are the snowmen props tagged properly?

**Comment by CounterCraftz** [comment]
Are they supposed to have a colon or semi colon? I haven't touched these once
 https://cdn.discordapp.com/attachments/450083646670503939/481434871659495424/Screenshot_20180821-080843.png

**Comment by Donkie** [comment]
semicolon, that looks correct

**Comment by Donkie** [comment]
Oh, apparantly only fm_rocket's can make the achievement go up. Do we still use that entity for rockets?

**Comment by CounterCraftz** [comment]
looked in the weapons repo and it uses "dod_bazooka_round"

**Comment by Donkie** [comment]
that's the problem then. fixed this for now. In the future, shit like this will be configured by my eventual gconfig addon which ya'll can use from ingame.
