### ISSUE TITLE
Harpoon - the ultimate weapon of destruction in One Weapon event.

### ISSUE THREAD

**Issue by lightclaw** [GMDevinity/FloodIssues#521]
### Description of bug
Since the weapon that will be used during the round is decided by random, you might get a Harpoon (or possibly Extinguisher?) that will result fun gameplay of voyaging around the map for 4 minutes and 30 seconds. 

### What I expected to happen
I wanted to shoot other people and play like a normal round but only with one weapon.

### What instead happened
I was doing nothing.

### Steps to reproduce
* Call One Weapon event vote
* Get One Weapon event
* Repeat the first step until you have Harpoon
* Enjoy your stay

### Extra info (evidence, logs, etc)
https://lc.dbot.serealia.ca/screenshots/2018/08/oneweapon.dem

**Comment by Donkie** [comment]
This shouldn't actually happen, you're always given one gun and the harpoon gun to go with it, however if the gun failed to be given (if counter removed it!!!) then it fails and you're only given the harpoon.
