### ISSUE TITLE
flag icon issues

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#522]
icon32/flagicons/half-life.png
icon32/flagicons/scp-foundation.png
icon32/flagicons/scp-taskforce.png

the system apparently does not recognize material files with dashes. every flag icon seems to be working except for those

on the day the summer event ends these files should have the dashes removed, or it could be fixed later on so that they are supported

**Comment by lightclaw** [comment]
why would you remove those when you can just remove 3 dashes in those? :thinking:
