### ISSUE TITLE
Setting M4 shotgun as default weapon

### ISSUE THREAD

**Issue by lightclaw** [GMDevinity/FloodIssues#524]
### Description of bug
Putting M4 combat shotgun will result in using SPAS as a first weapon once the round starts. 

### What I expected to happen
Have M4 in my hands.

### What instead happened
Other shotgun appears in my hands.

### Steps to reproduce
* Press Q
* Righ click on M4 Combat Shotgun
* Click on "Set as favourite"
* Wait for the new round
* Have SPAS in your hands

### Extra info (evidence, logs, etc)
Easily reproducable so I wont leave anything here.

**Comment by Donkie** [comment]
Fixed
