### ISSUE TITLE
Change default smart weld commands

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#530]
By default smartwelder_clearwelds is toggled to 1

I don't think this should be the case as it can easily ruin boat construction if you're stacking unfrozen props, building high towered structures or on the air

These should be the player defaults:
smartwelder_clearwelds 0 (not sure if this command is viable anymore with the weld tool having distance restrictions)
smartwelder_freeze 1

**Comment by Donkie** [comment]
Done
