### ISSUE TITLE
Broken Acid Water event

### ISSUE THREAD

**Issue by Snwstrm** [GMDevinity/FloodIssues#531]
### Description of bug
Some props don't take the damage
### What I expected to happen
Props supposed to be damaged by water while they floating in it.

### What instead happened
Props takes no dmg.

### Steps to reproduce
* Force acid water round
* Build some random boats
* When the round start you can see that some of ur props won't take dmg from water

### Extra info (evidence, logs, etc)
![20181003154410_1](https://user-images.githubusercontent.com/43098947/46427971-6e314f00-c74b-11e8-80f9-e666d4e48089.jpg)
![20181003154414_1](https://user-images.githubusercontent.com/43098947/46427995-7d180180-c74b-11e8-848d-6919e2eccd9f.jpg)
![20181003154415_1](https://user-images.githubusercontent.com/43098947/46428008-83a67900-c74b-11e8-9ec5-7b3e179010c5.jpg)
![20181003154418_1](https://user-images.githubusercontent.com/43098947/46428009-83a67900-c74b-11e8-893a-1da273509a5d.jpg)
![20181003154526_1](https://user-images.githubusercontent.com/43098947/46428010-843f0f80-c74b-11e8-86a2-efe2b30d0779.jpg)
![20181003154533_1](https://user-images.githubusercontent.com/43098947/46428011-843f0f80-c74b-11e8-8dbd-1c29ca5d9af5.jpg)

````
some
anime
here
````

**Comment by exotranc** [comment]
If a prop is completely still during the round, it will not take any damage. This issue has existed since the inception of this mode.

Additionally, some props like the boats (if flipped over) are not submerged enough to take damage.

**Comment by Donkie** [comment]
Should be fixed now 👍
