### ISSUE TITLE
Team names that have identical letters break the TAB screen.

### ISSUE THREAD

**Issue by lightclaw** [GMDevinity/FloodIssues#532]
### Description of bug
The bug happens once you make 2 teams with the same letters from the alphabet and it does not matter whether you use upper case letters or lower case ones.

### What I expected to happen
See 2 different teams

### What instead happened
Got a seizure

### Steps to reproduce
* Make team lets say "commUnism"
* Make team "communism"
*Press tab
### Extra info (evidence, logs, etc)
Here's a console error being spammed while I hold mouse click:
````
https://lc.dbotthepony.ru/screenshots/2018/12/tab.mp4
im not exactly sure what it is caused by, but around this
````

**Comment by Donkie** [comment]
I know what causes this, thank you

**Comment by Donkie** [comment]
Fixed
