### ISSUE TITLE
Anti-cheat banning due to the use of FPS configs 

### ISSUE THREAD

**Issue by lightclaw** [GMDevinity/FloodIssues#533]
### Description of bug
After installation of TF2 fps configs on the game with the goal of achieving better fps that isnt 80 during my gameplay on any server I've recieved a couple kicks/bans from anti-cheat with reason "Console variable manipulation" with various ban lenghts

### What instead happened
A ban happened

### Steps to reproduce
* Use FPS config
* Banned

### Console logs when I was using old chrismaxframes FPS config.
````
Disconnect: Banned by anticheat for 24 hours:
        Incident ID: STEAM_0:1:65200150/1523 (note this if you want to appeal)
        Reason: console variable manipulation.

````

### Cause?
I'm not exactly sure why it is happening since none of those configs disable any effects other than excess of particles, lightning and etc. without making them full bright wallhacks. Might as well be caused by bans difference in console variables that had been toggled in main menu under convar sv_cheats 1 and after joining the server it switches of causing the issue.
I've used medium high config when I got banned first time and it can be obtained here: https://mastercomfig.com/
The second time I got kicked I used this old cfg:
https://lc.dbotthepony.ru/screenshots/2019/01/autoexec.cfg

**Comment by Donkie** [comment]
CAC has been removed
