### ISSUE TITLE
Remove or alter server autorestart

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#537]
While it's a good idea that the automatic restart helps with the coexisting lag, it doesn't weigh into the loss of players this may have.

The server was pretty packed last night then the automatic restart came about and not even half of them show up anymore. This is a concerning issue considering players don't tend to stick around or alternatively automatically restart the server if there is no players on (which I think does that already)

This has the same toll on BR so I don't think it's worth losing our playerbase during peak times in order to subsidize the lag

**Comment by Donkie** [comment]
It's just a changelevel, how can this cause half the players to drop?
The restart is necessary due to how gmod works.

**Comment by CounterCraftz** [comment]
I'm not exactly sure why they choose not to stick around, but they just leave. It's not specific to this but other events as well.

If it's absolutely necessary to restart the server while more than half of the player slots is present then I think it should be adjusted in some way to circumvent the loss.

**Comment by Donkie** [comment]
Automatic restart no longer triggers for >4 players
