### ISSUE TITLE
Weapons tab - some minor suggestions 

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#540]
- [ ] Weapon description text is difficult to read on light surfaces
![image](https://user-images.githubusercontent.com/11022368/54064892-00e88500-41e7-11e9-9613-c9962f24d670.png)
---------------------
- [ ] Expand right click functionality beyond if the player owns the weapons

I think players should also be able to purchase weapons and sell weapons they already own using right click

**Comment by Donkie** [comment]
Fixed first one, I don't like your second idea, buying/selling is a seldom operation and shouldn't be that easily accessible
