### ISSUE TITLE
juggloadout tag not working properly

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#541]
### Description of bug
`juggloadout` weapon tag gives infinite ammo without also requiring `jugginfammo`
### What I expected to happen
`juggloadout` to give ammo respective to the database

### What instead happened
`juggloadout` gives infinite ammo

### Steps to reproduce
* tag a weapon `juggloadout`

### Extra info (evidence, logs, etc)

https://youtu.be/gGFXbkNM2Ik

![jLIuAfNqP5](https://user-images.githubusercontent.com/11022368/54065211-82daad00-41eb-11e9-91cf-f420173b8837.png)

**Comment by CounterCraftz** [comment]
nvm I'm retarded

**Comment by Donkie** [comment]
What did you do? @CounterCraftz

**Comment by CounterCraftz** [comment]
Was juggernaut on a populated server and noticed that the AWP gave regular ammo, I was testing it with d_giveallweaponsandammo and realized that the command gave infinite ammo. Felt so dumb lmao
