### ISSUE TITLE
Edit how dead props are displayed on teams

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#542]
Suggested idea: Mark all "unprofitable" props red if all teammates are dead, not individuals within a team.

Currently if a teammate is dead, their prop will also be marked. However an issue with this is that it can be very misleading as you are able to still gain profit off of a dead player's boat considering that the teammates are still alive (which should be the case; however the current system assumes that you cant) and creates general confusion of whoever else is left in the round.

https://www.youtube.com/watch?v=GqRMvr1r9HM

**Comment by Donkie** [comment]
Must be a bug then cause I'm pretty sure that's how I made it already.

**Comment by Donkie** [comment]
Fixed
