### ISSUE TITLE
Remove lamps 

### ISSUE THREAD

**Issue by lightclaw** [GMDevinity/FloodIssues#545]
### It kills fps for a majority of players in exchange for doubtful fun of those who can spawn them.
1 lamp on flood is enough to cause the issues.

### not_fun
````
https://lc.dbotthepony.ru/screenshots/2019/03/20190326231948_1.jpg
https://lc.dbotthepony.ru/screenshots/2019/03/20190326215907_1.jpg
````

**Comment by Donkie** [comment]
Lamps have been removed
