### ISSUE TITLE
Some weapon changes

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#559]
In conjunction with #548 and [this thread](https://devinity.org/threads/flood-weapons-suggestions-feedback.6551/page-2#post-46074)

- [x] Make neater categories
> Pistols, Submachine Guns, Rifles, Sniper Rifles, Shotguns, Heavy, Explosives, Melee, Special, Utilities, One-time (?), Round Event, Seasonal Event, Experimental
- [x] Weapon descriptions (would be nice if I could get some help on this one)
- [x] Order weapons by price ascending
> hateful meme suggested sorting them out by damage/accuracy
- [ ] Add limited ignition range for Trench gun or some random chance 
- [x] Community suggested velement weapons
> I hope to get through the rocket launcher that @Lime1248 made, Space Turtle's shotgun (mentioned) and some other community velement models that I get
- [ ] Look into fixing some broken weapon sounds, i.e: trench gun, g3, ssg, gol 
- [ ] Disable muzzleflash/bullet shells on the Pocket Launcher
- [ ] Fix the stick
> Doesn't deal player damage
- [ ] Pistols need better changes
- [x] P90 is too OP
> Damage and mag is too high; would also probably do some general smg changes too
- [x] Maybe disable weapon tooltip for consistency
- [ ] Add devinity selection icons for the rest of the sweps
- [ ] Replace the m249
- [ ] Add a heavy weapon
- [ ] Update some weapon hotkeys 
- [x] The eviscerator is too OP
- [x] The flamethrower is too OP
- [x] Weapons are too laggy when shooting

**Comment by lightclaw** [comment]
Replacements for:
- L85A2 to StG44 from the DoD pack (https://steamcommunity.com/sharedfiles/filedetails/?id=848335041)
- Minimi Para to MG42 from the DOI pack (https://steamcommunity.com/sharedfiles/filedetails/?id=1560419263) 

New weapons: 
- M1918 BAR from DOI pack (use stats from DoD pack)
- M1919 from DOI pack (use stats from DoD pack)
- Lewis gun from DOI pack
- FMG42 from DOI pack
