### ISSUE TITLE
Interactive with player ragdolls

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#560]
This was discussed a bit ingame and on #flood_chat and I think it would be nice to add some feature that would allow interaction with the bodies

Maybe players would be able to pick up the ragdolls and like throw it for a bit of fun while it's still present and they would also have an opportunity to replenish health from it (risk vs reward type of thing)

I'm wondering if this would be a good idea or if there's anything else that would make this concept more interesting beyond it being a SWEP

**Comment by Donkie** [comment]
I don't get it, why would flood which is quite far away from a RP gamemode contain a hands swep?

**Comment by CounterCraftz** [comment]
I was thinking of it more as a side utility that has a risk reward benefit rather than some RP thing

**Comment by CounterCraftz** [comment]
I was also thinking maybe this would better coincide with making additions to fists swep instead since it doesn't really do anything, but my general concept is to allow some type of interaction with the ragdolls for a bit of fun

**Comment by Lime1248** [comment]
To piggyback off of Counter's idea, I think it's creative. I look at it as a way to make the game more exciting, especially if someone were able to discover that you could interact with players' dead bodies would make someone go, "Wow, that's cool they would add something like that" without it having a huge impact to the game. I would suggest something like "looting" dead bodies for 'medkits' (basically small health regeneration automatically applied) and ammo if that were to be added. Clearly this isn't by all means a priority, but I see it as how little things can make a big difference in fun and creativity.

**Comment by CounterCraftz** [comment]
I think looting them would be a bit of a better alternative to consider than a SWEP. You see a dead body and you rush to it before it gets completely eaten by the piranhas (despawns)

You take some health but you get something in return depending on the distance or whatever, I always thought it would be nice to encourage players to become more proactive like we have with the melees and such
