### ISSUE TITLE
Unwelding

### ISSUE THREAD

**Issue by RicksBeehive** [GMDevinity/FloodIssues#569]
Unwelding is so rare it's practically non-existent, and I think the rate should be increased to what it was before.

**Comment by Donkie** [comment]
The new unwelding system is more intricate, I'm not sure if you remember. The system factors in the health of the two props involved, and also metal<->metal welds are unbreakable.

Basically, if one of the two props involved has very little health left, the weld is considered to be of poor condition and thus have a lot higher chance breaking than a weld between two undamaged props.

Pseudocode of the algorithm:
`prop1PercentHealth = prop1Health / prop1MaxHealth
prop2PercentHealth = prop2Health / prop2MaxHealth

weakest = min(prop1PercentHealth, prop2PercentHealth)

chanceOfSurviving = weakest / power`
Where power is most often 1, but for more powerful weapons like predator it's 2.

**Comment by Donkie** [comment]
@RicksBeehive Closing this unless you have anything more to add.
