### ISSUE TITLE
Add a vote "no" option

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/FloodIssues#60]
I would like the ability to say "No" to a vote. This vote should be visible to all players to see. It will allow me to see how many people disagree with my vote. 

IE:

Donkie starts a vote for a random event. Out of 15 people, 4 vote **yes**, 2 vote **no** and 9 don't vote

Making majority vote fail.

**Comment by CounterCraftz** [comment]
Well it is kinda obvious who 'voted no'. (if people don't f3)

**Comment by Donkie** [comment]
This goes far down the priority list
