### ISSUE TITLE
Option to clientside mute chat.

### ISSUE THREAD

**Issue by jeffreythe00** [GMDevinity/FloodIssues#72]
We need the option to clientside mute people in chat.
- Option to target and mute a player/s
- Option to /ignore [name] - **This should clientside mute AND gag the target**

**Comment by jeffreythe00** [comment]
http://devinity.org/threads/optional-gag-button.3397/unread

**Comment by Donkie** [comment]
How should this be different from voice muting, how will you be able to tell a difference? Voice muting is easily seen in scoreboard

**Comment by jeffreythe00** [comment]
Works like this.

Donkie says: Nigger
Jeff: /ignore donkie
Donkie says: Nigger
Jeff doesn't see it because anything donkie says in chat is now filtered.

**Comment by Donkie** [comment]
How do I know Donkie is now muted?

**Comment by jeffreythe00** [comment]
Make anything Donkie says in chat obfuscated. 

What everyone sees
Donkie: Nigger
What Jeff sees
Donkie: ****** (Jeff now knows donkie has said something but can't know because it is obfuscated.)

Add a mute chat icon like such. 
![chrome_2016-07-31_11-11-22](https://cloud.githubusercontent.com/assets/6297372/17277415/3df1255c-5710-11e6-8cfd-31e0835e8062.png)

**Comment by Donkie** [comment]
any reason this should remain? voice muting is understandable because its annoying as fuck, but chat spam isn't very annoying
